/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import ui.Accueil;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import nf.Code;
import nf.LocalisationExamen;
import nf.Patient;
import nf.Professionnel;
import nf.TypeExam;
/**
 *
 * @author Julie
 */
public class EnregistrerExamen extends javax.swing.JFrame {
    private Controler controler;
    /**
     * Creates new form EnregistrerExamen
     */
    public EnregistrerExamen(Controler controler) {
        this.controler=controler;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        EnregistrerText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Valider = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        NomExamen = new javax.swing.JLabel();
        DoseExamen = new javax.swing.JLabel();
        TypeExamen = new javax.swing.JComboBox<>();
        ValeurDose = new javax.swing.JTextField();
        typeDose = new javax.swing.JLabel();
        DateExamenLabel = new javax.swing.JLabel();
        DateExamenFinTextField = new javax.swing.JTextField();
        NumeroArchivageLabel = new javax.swing.JLabel();
        notesField = new javax.swing.JTextField();
        MedecinLabel = new javax.swing.JLabel();
        MedecinFieldNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        DateExamenDebutTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MedecinFieldPrenom = new javax.swing.JTextField();
        NumeroArchivageLabel1 = new javax.swing.JLabel();
        localisationExamen = new javax.swing.JComboBox<>();
        salleField = new javax.swing.JTextField();
        DoseExamen1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        heureFin = new javax.swing.JTextField();
        heureDebut = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EnregistrerText.setText("ENREGISTRER UN EXAMEN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(EnregistrerText, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(EnregistrerText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(160, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        Valider.setText("VALIDER");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 1, 20);
        jPanel2.add(Valider, gridBagConstraints);

        Annuler.setText("ANNULER");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 0);
        jPanel2.add(Annuler, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        NomExamen.setText("Type de l'examen");

        DoseExamen.setText("Dose de l'examen");

        TypeExamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "échographie", "IRM", "radiographie", "scanner", "scintigraphie" }));
        TypeExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeExamenActionPerformed(evt);
            }
        });

        ValeurDose.setText("0");
        ValeurDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValeurDoseActionPerformed(evt);
            }
        });

        DateExamenLabel.setText("Date de début de l'examen (JJ/MM/AAAA)");

        DateExamenFinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateExamenFinTextFieldActionPerformed(evt);
            }
        });

        NumeroArchivageLabel.setText("Notes");

        notesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesFieldActionPerformed(evt);
            }
        });

        MedecinLabel.setText("Médecin prescripteur : Nom");

        MedecinFieldNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedecinFieldNomActionPerformed(evt);
            }
        });

        jLabel1.setText("Date de fin de l'examen (JJ/MM/AAAA)");

        DateExamenDebutTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateExamenDebutTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Prenom");

        MedecinFieldPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedecinFieldPrenomActionPerformed(evt);
            }
        });

        NumeroArchivageLabel1.setText("Localisation");

        localisationExamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cérébral", "cervical", "membre_supérieur", "membre_inférieur", "thoracique", "abdomino_pelvien", "abdominal", "pelvien", "osseux", "cardiaque" }));
        localisationExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localisationExamenActionPerformed(evt);
            }
        });

        salleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salleFieldActionPerformed(evt);
            }
        });

        DoseExamen1.setText("Salle");

        jLabel3.setText("Heure (HH:MM)");

        heureFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heureFinActionPerformed(evt);
            }
        });

        heureDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heureDebutActionPerformed(evt);
            }
        });

        jLabel4.setText("Heure (HH:MM)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateExamenDebutTextField)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TypeExamen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NomExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DateExamenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(salleField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DoseExamen1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(heureDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DoseExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(localisationExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumeroArchivageLabel1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DateExamenFinTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(ValeurDose, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heureFin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(typeDose))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notesField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(MedecinLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NumeroArchivageLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MedecinFieldNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MedecinFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(39, 39, 39)))
                .addGap(77, 77, 77))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomExamen)
                    .addComponent(NumeroArchivageLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TypeExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DoseExamen1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(localisationExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DoseExamen)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValeurDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(typeDose)
                        .addComponent(salleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateExamenLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateExamenFinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateExamenDebutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heureFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heureDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NumeroArchivageLabel)
                .addGap(18, 18, 18)
                .addComponent(notesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedecinLabel)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MedecinFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MedecinFieldPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        Date dateDebut = new Date();
        Date dateFin = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyyHH:mm");
        SimpleDateFormat formatDateTimeBDD = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        double dose_exam = Double.parseDouble(ValeurDose.getText());
        String libelleDose = typeDose.getText();
        LocalisationExamen localisation_examen = LocalisationExamen.valueOf(localisationExamen.getSelectedItem().toString());
        String notes = notesField.getText();
        int salle= Integer.parseInt(salleField.getText());
        String date_debut =  DateExamenDebutTextField.getText()+heureDebut.getText();
        try {
            dateDebut=sdf.parse(date_debut);
        } catch (ParseException ex) {
            Logger.getLogger(EnregistrerExamen.class.getName()).log(Level.SEVERE, null, ex);
        }
        String date_fin = DateExamenFinTextField.getText()+heureFin.getText();
        try {
            dateFin = sdf.parse(date_fin);
        } catch (ParseException ex) {
            Logger.getLogger(EnregistrerExamen.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dateDebutBDD = formatDateTimeBDD.format(dateDebut);
        String dateFinBDD = formatDateTimeBDD.format(dateFin);
        Professionnel medecin = controler.getSir().chercherProfessionnel(MedecinFieldNom.getText(),MedecinFieldPrenom.getText());//relier BDD
        TypeExam type = TypeExam.valueOf(TypeExamen.getSelectedItem().toString());
        Patient p = controler.getCurrentPatient();
        controler.ajouterExamBDD(type,localisation_examen,notes,dateDebutBDD,dateFinBDD,salle,dose_exam,libelleDose,p.getIdPatient(),medecin, Code.enregistrement);
        this.dispose();
        controler.refreshDMR();
    }//GEN-LAST:event_ValiderActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_AnnulerActionPerformed

    private void TypeExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeExamenActionPerformed
        if (TypeExamen.getSelectedItem().equals(TypeExam.IRM.toString())){
            typeDose.setText("Telsa");
            this.repaint();
        }
        if (TypeExamen.getSelectedItem().equals(TypeExam.scanner.toString())){
            typeDose.setText("mSv");
            this.repaint();
        }
        if (TypeExamen.getSelectedItem().equals(TypeExam.scintigraphie.toString())){
            typeDose.setText("µSv/MBq");
            this.repaint();
        }if (TypeExamen.getSelectedItem().equals(TypeExam.radiographie.toString())){
            typeDose.setText("Gy/cm²");
            typeDose.repaint();
        }if (TypeExamen.getSelectedItem().equals(TypeExam.échographie.toString())){
            typeDose.setText("");
            typeDose.repaint();
            
        }
        
        
    }//GEN-LAST:event_TypeExamenActionPerformed

    private void ValeurDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValeurDoseActionPerformed
                
    }//GEN-LAST:event_ValeurDoseActionPerformed

    private void DateExamenFinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateExamenFinTextFieldActionPerformed
        
    }//GEN-LAST:event_DateExamenFinTextFieldActionPerformed

    private void notesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesFieldActionPerformed
        
    }//GEN-LAST:event_notesFieldActionPerformed

    private void MedecinFieldNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedecinFieldNomActionPerformed
        
    }//GEN-LAST:event_MedecinFieldNomActionPerformed

    private void DateExamenDebutTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateExamenDebutTextFieldActionPerformed
        
    }//GEN-LAST:event_DateExamenDebutTextFieldActionPerformed

    private void MedecinFieldPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedecinFieldPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedecinFieldPrenomActionPerformed

    private void localisationExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localisationExamenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localisationExamenActionPerformed

    private void salleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salleFieldActionPerformed

    private void heureFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heureFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heureFinActionPerformed

    private void heureDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heureDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heureDebutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnregistrerExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnregistrerExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnregistrerExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnregistrerExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new EnregistrerExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JTextField DateExamenDebutTextField;
    private javax.swing.JTextField DateExamenFinTextField;
    private javax.swing.JLabel DateExamenLabel;
    private javax.swing.JLabel DoseExamen;
    private javax.swing.JLabel DoseExamen1;
    private javax.swing.JLabel EnregistrerText;
    private javax.swing.JTextField MedecinFieldNom;
    private javax.swing.JTextField MedecinFieldPrenom;
    private javax.swing.JLabel MedecinLabel;
    private javax.swing.JLabel NomExamen;
    private javax.swing.JLabel NumeroArchivageLabel;
    private javax.swing.JLabel NumeroArchivageLabel1;
    private javax.swing.JComboBox<String> TypeExamen;
    private javax.swing.JTextField ValeurDose;
    private javax.swing.JButton Valider;
    private javax.swing.JTextField heureDebut;
    private javax.swing.JTextField heureFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> localisationExamen;
    private javax.swing.JTextField notesField;
    private javax.swing.JTextField salleField;
    private javax.swing.JLabel typeDose;
    // End of variables declaration//GEN-END:variables
}
