/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import nf.Professionnel;

/**
 *
 * @author Julie
 */
public class CreerDMR extends javax.swing.JFrame {
    Accueil a;
    /**
     * Creates new form CreerDMR
     */
    public CreerDMR(Accueil a) {
        this.a = a;
        initComponents();
        this.setTitle("Création d'un DMR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nom_usuel_field = new javax.swing.JTextField();
        nom_naiss_field = new javax.swing.JTextField();
        prenom_field = new javax.swing.JTextField();
        nss_field = new javax.swing.JTextField();
        date_field = new javax.swing.JTextField();
        adresse_field = new javax.swing.JTextField();
        tel_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        FemmeRadioButton = new javax.swing.JRadioButton();
        HommeRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Veuillez renseigner les informations concernant le patient");

        nom_usuel_field.setMinimumSize(new java.awt.Dimension(150, 20));
        nom_usuel_field.setPreferredSize(new java.awt.Dimension(150, 20));

        nom_naiss_field.setMinimumSize(new java.awt.Dimension(150, 20));
        nom_naiss_field.setPreferredSize(new java.awt.Dimension(150, 20));

        prenom_field.setMinimumSize(new java.awt.Dimension(150, 20));
        prenom_field.setPreferredSize(new java.awt.Dimension(150, 20));

        nss_field.setMinimumSize(new java.awt.Dimension(150, 20));
        nss_field.setPreferredSize(new java.awt.Dimension(150, 20));

        date_field.setMinimumSize(new java.awt.Dimension(150, 20));
        date_field.setPreferredSize(new java.awt.Dimension(150, 20));

        adresse_field.setMinimumSize(new java.awt.Dimension(150, 20));
        adresse_field.setPreferredSize(new java.awt.Dimension(150, 20));

        tel_field.setMinimumSize(new java.awt.Dimension(150, 20));
        tel_field.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel2.setText("Nom usuel*");

        jLabel3.setText("Nom de naissance");

        jLabel4.setText("Date de naissance* (jj/mm/aaaa)");

        jLabel5.setText("Numéro de sécurité sociale*");

        jLabel6.setText("Prénom*");

        jLabel7.setText("Adresse postale*");

        jLabel8.setText("Téléphone*");

        jLabel9.setText("Genre* :");

        jLabel10.setText("Les champs marqués par * sont obligatoires");

        Valider.setText("Valider");
        Valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValiderMouseClicked(evt);
            }
        });

        Annuler.setText("Annuler");
        Annuler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerMouseClicked(evt);
            }
        });

        buttonGroup1.add(FemmeRadioButton);
        FemmeRadioButton.setText("Femme");

        buttonGroup1.add(HommeRadioButton);
        HommeRadioButton.setText("Homme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom_usuel_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(FemmeRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HommeRadioButton))
                        .addComponent(date_field, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tel_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_naiss_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nss_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresse_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(56, 56, 56)
                        .addComponent(Valider)
                        .addGap(18, 18, 18)
                        .addComponent(Annuler)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nom_usuel_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nom_naiss_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenom_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nss_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adresse_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tel_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FemmeRadioButton)
                    .addComponent(HommeRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Valider)
                    .addComponent(Annuler))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerMouseClicked
        this.dispose();
    }//GEN-LAST:event_AnnulerMouseClicked

    private void ValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValiderMouseClicked
        String champsVides = "";
        String champsTropLongs = "";
        String nomNaissance = nom_naiss_field.getText();
        if (nomNaissance.length() > 30) {
            champsTropLongs += "Le nom de naissance ne doit pas dépasser 30 caractères";
        }
        String nomUsuel = nom_usuel_field.getText();
        if (nomUsuel.isEmpty()) {
            champsVides += "\nNom usuel";
        }
        if (nomUsuel.length() > 30) {
            champsTropLongs += "Le nom usuel ne doit pas dépasser 30 caractères";
        }
        String prenom = prenom_field.getText();
        if (prenom.isEmpty()) {
            champsVides += "\nPrenom";
        }
        if (prenom.length() > 30){
            champsTropLongs += "Le prénom ne doit pas dépasser 30 caractères";
        }
        SimpleDateFormat formatFormulaire = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat formatBDD = new SimpleDateFormat("yyyy-MM-dd");
        String dateDeNaissance="";
        try {
            Date date=formatFormulaire.parse(date_field.getText());
            dateDeNaissance=formatBDD.format(date);
        } catch (ParseException ex) {
            Logger.getLogger(CreerDMR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (dateDeNaissance.isEmpty()) {
            champsVides += "\nNom usuel";
        }
        String genre ;
        if(FemmeRadioButton.isSelected()){
        genre = "Femme";
        }
        else{
            genre = "Homme";
        }
        String nss = nss_field.getText();
        if (nss.isEmpty()) {
            champsVides += "\nNuméro de sécurité sociale";
        }
        if (nss.length() > 45) {
                champsTropLongs += "Le numéro ne doit pas dépasser 60 caractère";
            }
        String tel = tel_field.getText();
        if (tel.isEmpty()) {
            champsVides += "\nTéléphone";
        }
        if (tel.length() > 10) {
                champsTropLongs += "Le téléphone ne doit pas dépasser 10 caractère";
            }
        String adresse = adresse_field.getText();
        if (adresse.isEmpty()) {
            champsVides += "\nLieu de naissance";
        }
        if (adresse.length() > 60) {
                champsTropLongs += "L'adresse ne doit pas dépasser 60 caractère";
            }
        if (champsVides.equals("") && champsTropLongs.equals("")) {
            //récupere l'id patient a partir de la base de donnees
            boolean b = a.getSir().ajouterPatientBDD(nomNaissance, nomUsuel, prenom, nss, tel, adresse, dateDeNaissance, genre);
            if(b){
            Professionnel p = a.getCurrentUser();
            a.dispose();
            a = new Accueil(p);
            a.setVisible(true);
            this.dispose();
            }
            else{
                new Erreur("Le patient a déjà été rentré");
            }
        }
        else {
            champsVides="Les champs suivants n'ont pas été renseignés :"+champsVides;
            new Erreur(champsVides+"\n"+champsTropLongs).setVisible(true);
        }
    }//GEN-LAST:event_ValiderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreerDMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreerDMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreerDMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreerDMR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CreerDMR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton FemmeRadioButton;
    private javax.swing.JRadioButton HommeRadioButton;
    private javax.swing.JButton Valider;
    private javax.swing.JTextField adresse_field;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField date_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom_naiss_field;
    private javax.swing.JTextField nom_usuel_field;
    private javax.swing.JTextField nss_field;
    private javax.swing.JTextField prenom_field;
    private javax.swing.JTextField tel_field;
    // End of variables declaration//GEN-END:variables
}
